# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-26 02:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('estado_1', models.CharField(default=b'TO_DO', max_length=5)),
                ('estado_2', models.CharField(default=b'DOING', max_length=5)),
                ('estado_3', models.CharField(default=b'DONE', max_length=5)),
                ('orden', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=32, unique=True)),
                ('direccion', models.CharField(max_length=70)),
                ('telefono', models.CharField(max_length=70)),
                ('observacion', models.TextField(max_length=200)),
                ('correo', models.CharField(max_length=70)),
                ('estado', models.CharField(choices=[(b'ACTIVO', b'Activo'), (b'INACTIVO', b'Inactivo')], default=b'ACT', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('dato', models.BinaryField()),
            ],
        ),
        migrations.CreateModel(
            name='Flujo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60, unique=True)),
                ('descripcion', models.CharField(max_length=200, unique=True)),
                ('actividades', models.ManyToManyField(related_name='actividades', to='sgpa.Actividad')),
            ],
        ),
        migrations.CreateModel(
            name='Historia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('usuario', models.CharField(max_length=60)),
                ('fecha', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Hu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=32)),
                ('observacion', models.TextField(max_length=200)),
                ('valornegocio', models.IntegerField(default=1)),
                ('valortecnico', models.IntegerField(default=1)),
                ('hora', models.PositiveIntegerField(default=1)),
                ('estadorevision', models.CharField(choices=[(b'PEN', b'Pendiante'), (b'APR', b'Aprobado'), (b'REC', b'Rechazado')], default=b'PEN', max_length=20)),
                ('estadodesarrolllo', models.CharField(choices=[(b'SUS', b'Suspender'), (b'PRO', b'Procesar')], default=b'PRO', max_length=20)),
                ('estadoflujo', models.CharField(choices=[(b'TOD', b'To Do'), (b'DOI', b'Doing'), (b'DON', b'Done')], default=b'TOD', max_length=20)),
                ('prioridad', models.IntegerField(default=1)),
                ('priorizacion', models.IntegerField(default=1)),
                ('actividad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sgpa.Actividad')),
                ('flujo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flujo', to='sgpa.Flujo')),
            ],
        ),
        migrations.CreateModel(
            name='Permiso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60, unique=True)),
                ('descripcion', models.CharField(max_length=120)),
                ('tipo', models.CharField(choices=[(b'SISTEMA', b'Sistema'), (b'PROYECTO', b'Proyecto')], default=b'SISTEMA', max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaInicio', models.CharField(max_length=20)),
                ('fechaFin', models.CharField(max_length=20)),
                ('fechaMod', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=32, unique=True)),
                ('estado', models.CharField(choices=[(b'PENDIENTE', b'Pendiente'), (b'ANULADO', b'Anulado'), (b'ACTIVO', b'Activo'), (b'FINALIZADO', b'Finalizado')], default=b'PENDIENTE', max_length=20)),
                ('cliente', models.ForeignKey(default=b'', on_delete=django.db.models.deletion.CASCADE, to='sgpa.Cliente')),
                ('flujo', models.ManyToManyField(related_name='flujopro', to='sgpa.Flujo')),
                ('lider', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lider', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60, unique=True)),
                ('descripcion', models.CharField(max_length=120)),
                ('tipo', models.CharField(choices=[(b'SISTEMA', b'Sistema'), (b'PROYECTO', b'Proyecto')], max_length=8)),
                ('permisos', models.ManyToManyField(to='sgpa.Permiso')),
            ],
        ),
        migrations.CreateModel(
            name='Sprint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duracion', models.IntegerField(default=1)),
                ('fechaInicio', models.CharField(max_length=50)),
                ('fechaFin', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=60)),
                ('estado', models.CharField(choices=[(b'ACT', b'Activo'), (b'INA', b'Inactivo')], default=b'INA', max_length=20)),
                ('hu', models.ManyToManyField(related_name='hu', to='sgpa.Hu')),
                ('proyecto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project', to='sgpa.Proyecto')),
            ],
        ),
        migrations.CreateModel(
            name='Trabajo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('horas', models.CharField(max_length=60)),
                ('fecha', models.CharField(max_length=60)),
                ('nota', models.TextField(max_length=200)),
                ('actor', models.CharField(max_length=60)),
                ('filename', models.CharField(max_length=60, null=True)),
                ('size', models.IntegerField(null=True)),
                ('flujo', models.CharField(max_length=60)),
                ('actividad', models.CharField(max_length=60)),
                ('estado', models.CharField(max_length=60)),
                ('sprint', models.CharField(max_length=60)),
                ('archivo', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='archivo', to='sgpa.Files')),
                ('hu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historiatrabajo', to='sgpa.Hu')),
            ],
        ),
        migrations.AddField(
            model_name='hu',
            name='proyecto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proyecto', to='sgpa.Proyecto'),
        ),
        migrations.AddField(
            model_name='hu',
            name='responsable',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responsable', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historia',
            name='hu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hishu', to='sgpa.Hu'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='proyecto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proyectoequipo', to='sgpa.Proyecto'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='rol',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rolequipo', to='sgpa.Rol'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarioequipo', to=settings.AUTH_USER_MODEL),
        ),
    ]
